/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#ffffff',
        'primary-container': '#3b3b3b',
        'surface-variant': '#e2e2e2',
        'on-background': '#1a1c1c',
        'surface-container-high': '#e8e8e8',
        outline: '#777777',
        surface: '#f9f9f9',
        'on-secondary-fixed-variant': '#3b3b3b',
        error: '#ba1a1a',
        primary: '#000000',
        'on-tertiary': '#e2e2e2',
        background: '#f9f9f9',
        'inverse-primary': '#c6c6c6',
        'surface-container-low': '#f3f3f3',
        'surface-container-highest': '#e2e2e2',
        'on-tertiary-container': '#ffffff',
        'on-surface-variant': '#474747',
        'secondary-fixed': '#c8c6c6',
        'primary-fixed': '#5e5e5e',
        'on-tertiary-fixed-variant': '#e2e2e2',
        'surface-tint': '#5e5e5e',
        'tertiary-container': '#737575',
        'surface-dim': '#dadada',
        'on-primary': '#e2e2e2',
        'surface-container-lowest': '#ffffff',
        tertiary: '#3a3c3c',
        'on-error-container': '#410002',
        'on-primary-fixed-variant': '#e2e2e2',
        'on-tertiary-fixed': '#ffffff',
        'secondary-container': '#d6d4d3',
        'tertiary-fixed-dim': '#454747',
        'on-primary-container': '#ffffff',
        'inverse-surface': '#2f3131',
        'on-secondary-fixed': '#1b1c1c',
        'secondary-fixed-dim': '#acabaa',
        'on-secondary-container': '#1b1c1c',
        secondary: '#5f5e5e',
        'on-secondary': '#ffffff',
        'outline-variant': '#c6c6c6',
        'primary-fixed-dim': '#474747',
        'tertiary-fixed': '#5d5f5f',
        'surface-bright': '#f9f9f9',
        'on-error': '#ffffff',
        'surface-container': '#eeeeee',
        'on-surface': '#1a1c1c',
        'inverse-on-surface': '#f1f1f1',
        'error-container': '#ffdad6',
      },
      fontFamily: {
        headline: ['Inter'],
        body: ['Newsreader'],
        label: ['Inter'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
